#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path

def load_tools(ctx):
    ctx.load('compiler_cxx')

def options(ctx):
    load_tools(ctx)

def configure(ctx):
    load_tools(ctx)

    ctx.load('conanbuildinfo_waf', tooldir=[".", path.join(ctx.bldnode.abspath(), "..")]);

def build(bld):
    #Compile an executable from cpp files on source dir
    bld.program(
        target   = 'example',
        source   = "example.cpp",
        includes = ['.'],
        ldflags  = ['-pthread'],
        use      = bld.env.conan_dependencies)
